// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/postreport/postreport.proto

package postreport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        int32                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Reporter      string                 `protobuf:"bytes,3,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportTo      string                 `protobuf:"bytes,4,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostReport) Reset() {
	*x = PostReport{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReport) ProtoMessage() {}

func (x *PostReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReport.ProtoReflect.Descriptor instead.
func (*PostReport) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{0}
}

func (x *PostReport) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostReport) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostReport) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *PostReport) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

func (x *PostReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PostReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PostReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePostReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Reporter      string                 `protobuf:"bytes,2,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportTo      string                 `protobuf:"bytes,3,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReportRequest) Reset() {
	*x = CreatePostReportRequest{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReportRequest) ProtoMessage() {}

func (x *CreatePostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReportRequest.ProtoReflect.Descriptor instead.
func (*CreatePostReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostReportRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostReportRequest) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *CreatePostReportRequest) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

func (x *CreatePostReportRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CreatePostReportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreatePostReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostReport    *PostReport            `protobuf:"bytes,1,opt,name=post_report,json=postReport,proto3" json:"post_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReportResponse) Reset() {
	*x = CreatePostReportResponse{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReportResponse) ProtoMessage() {}

func (x *CreatePostReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReportResponse.ProtoReflect.Descriptor instead.
func (*CreatePostReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostReportResponse) GetPostReport() *PostReport {
	if x != nil {
		return x.PostReport
	}
	return nil
}

type FindPostReportByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPostReportByIDRequest) Reset() {
	*x = FindPostReportByIDRequest{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPostReportByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPostReportByIDRequest) ProtoMessage() {}

func (x *FindPostReportByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPostReportByIDRequest.ProtoReflect.Descriptor instead.
func (*FindPostReportByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{3}
}

func (x *FindPostReportByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindPostReportByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostReport    *PostReport            `protobuf:"bytes,1,opt,name=post_report,json=postReport,proto3" json:"post_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPostReportByIDResponse) Reset() {
	*x = FindPostReportByIDResponse{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPostReportByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPostReportByIDResponse) ProtoMessage() {}

func (x *FindPostReportByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPostReportByIDResponse.ProtoReflect.Descriptor instead.
func (*FindPostReportByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{4}
}

func (x *FindPostReportByIDResponse) GetPostReport() *PostReport {
	if x != nil {
		return x.PostReport
	}
	return nil
}

type FindAllPostReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllPostReportsRequest) Reset() {
	*x = FindAllPostReportsRequest{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllPostReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostReportsRequest) ProtoMessage() {}

func (x *FindAllPostReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostReportsRequest.ProtoReflect.Descriptor instead.
func (*FindAllPostReportsRequest) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{5}
}

type FindAllPostReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostReports   []*PostReport          `protobuf:"bytes,1,rep,name=post_reports,json=postReports,proto3" json:"post_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllPostReportsResponse) Reset() {
	*x = FindAllPostReportsResponse{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllPostReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostReportsResponse) ProtoMessage() {}

func (x *FindAllPostReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostReportsResponse.ProtoReflect.Descriptor instead.
func (*FindAllPostReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllPostReportsResponse) GetPostReports() []*PostReport {
	if x != nil {
		return x.PostReports
	}
	return nil
}

type PatchPostReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        int32                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Reporter      string                 `protobuf:"bytes,3,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportTo      string                 `protobuf:"bytes,4,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchPostReportRequest) Reset() {
	*x = PatchPostReportRequest{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchPostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchPostReportRequest) ProtoMessage() {}

func (x *PatchPostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchPostReportRequest.ProtoReflect.Descriptor instead.
func (*PatchPostReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{7}
}

func (x *PatchPostReportRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchPostReportRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PatchPostReportRequest) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *PatchPostReportRequest) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

func (x *PatchPostReportRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PatchPostReportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PatchPostReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostReport    *PostReport            `protobuf:"bytes,1,opt,name=post_report,json=postReport,proto3" json:"post_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchPostReportResponse) Reset() {
	*x = PatchPostReportResponse{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchPostReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchPostReportResponse) ProtoMessage() {}

func (x *PatchPostReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchPostReportResponse.ProtoReflect.Descriptor instead.
func (*PatchPostReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{8}
}

func (x *PatchPostReportResponse) GetPostReport() *PostReport {
	if x != nil {
		return x.PostReport
	}
	return nil
}

type DeletePostReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReportRequest) Reset() {
	*x = DeletePostReportRequest{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReportRequest) ProtoMessage() {}

func (x *DeletePostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReportRequest.ProtoReflect.Descriptor instead.
func (*DeletePostReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePostReportRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePostReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReportResponse) Reset() {
	*x = DeletePostReportResponse{}
	mi := &file_proto_postreport_postreport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReportResponse) ProtoMessage() {}

func (x *DeletePostReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postreport_postreport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReportResponse.ProtoReflect.Descriptor instead.
func (*DeletePostReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_postreport_postreport_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePostReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_postreport_postreport_proto protoreflect.FileDescriptor

const file_proto_postreport_postreport_proto_rawDesc = "" +
	"\n" +
	"!proto/postreport/postreport.proto\x12\n" +
	"postreport\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\n" +
	"PostReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x05R\x06postId\x12\x1a\n" +
	"\breporter\x18\x03 \x01(\tR\breporter\x12\x1b\n" +
	"\treport_to\x18\x04 \x01(\tR\breportTo\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x01\n" +
	"\x17CreatePostReportRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x1a\n" +
	"\breporter\x18\x02 \x01(\tR\breporter\x12\x1b\n" +
	"\treport_to\x18\x03 \x01(\tR\breportTo\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"S\n" +
	"\x18CreatePostReportResponse\x127\n" +
	"\vpost_report\x18\x01 \x01(\v2\x16.postreport.PostReportR\n" +
	"postReport\"+\n" +
	"\x19FindPostReportByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"U\n" +
	"\x1aFindPostReportByIDResponse\x127\n" +
	"\vpost_report\x18\x01 \x01(\v2\x16.postreport.PostReportR\n" +
	"postReport\"\x1b\n" +
	"\x19FindAllPostReportsRequest\"W\n" +
	"\x1aFindAllPostReportsResponse\x129\n" +
	"\fpost_reports\x18\x01 \x03(\v2\x16.postreport.PostReportR\vpostReports\"\xaa\x01\n" +
	"\x16PatchPostReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x05R\x06postId\x12\x1a\n" +
	"\breporter\x18\x03 \x01(\tR\breporter\x12\x1b\n" +
	"\treport_to\x18\x04 \x01(\tR\breportTo\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"R\n" +
	"\x17PatchPostReportResponse\x127\n" +
	"\vpost_report\x18\x01 \x01(\v2\x16.postreport.PostReportR\n" +
	"postReport\")\n" +
	"\x17DeletePostReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"4\n" +
	"\x18DeletePostReportResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf7\x03\n" +
	"\x11PostReportService\x12]\n" +
	"\x10CreatePostReport\x12#.postreport.CreatePostReportRequest\x1a$.postreport.CreatePostReportResponse\x12c\n" +
	"\x12FindPostReportByID\x12%.postreport.FindPostReportByIDRequest\x1a&.postreport.FindPostReportByIDResponse\x12c\n" +
	"\x12FindAllPostReports\x12%.postreport.FindAllPostReportsRequest\x1a&.postreport.FindAllPostReportsResponse\x12Z\n" +
	"\x0fPatchPostReport\x12\".postreport.PatchPostReportRequest\x1a#.postreport.PatchPostReportResponse\x12]\n" +
	"\x10DeletePostReport\x12#.postreport.DeletePostReportRequest\x1a$.postreport.DeletePostReportResponseB\x12Z\x10proto/postreportb\x06proto3"

var (
	file_proto_postreport_postreport_proto_rawDescOnce sync.Once
	file_proto_postreport_postreport_proto_rawDescData []byte
)

func file_proto_postreport_postreport_proto_rawDescGZIP() []byte {
	file_proto_postreport_postreport_proto_rawDescOnce.Do(func() {
		file_proto_postreport_postreport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_postreport_postreport_proto_rawDesc), len(file_proto_postreport_postreport_proto_rawDesc)))
	})
	return file_proto_postreport_postreport_proto_rawDescData
}

var file_proto_postreport_postreport_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_postreport_postreport_proto_goTypes = []any{
	(*PostReport)(nil),                 // 0: postreport.PostReport
	(*CreatePostReportRequest)(nil),    // 1: postreport.CreatePostReportRequest
	(*CreatePostReportResponse)(nil),   // 2: postreport.CreatePostReportResponse
	(*FindPostReportByIDRequest)(nil),  // 3: postreport.FindPostReportByIDRequest
	(*FindPostReportByIDResponse)(nil), // 4: postreport.FindPostReportByIDResponse
	(*FindAllPostReportsRequest)(nil),  // 5: postreport.FindAllPostReportsRequest
	(*FindAllPostReportsResponse)(nil), // 6: postreport.FindAllPostReportsResponse
	(*PatchPostReportRequest)(nil),     // 7: postreport.PatchPostReportRequest
	(*PatchPostReportResponse)(nil),    // 8: postreport.PatchPostReportResponse
	(*DeletePostReportRequest)(nil),    // 9: postreport.DeletePostReportRequest
	(*DeletePostReportResponse)(nil),   // 10: postreport.DeletePostReportResponse
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_proto_postreport_postreport_proto_depIdxs = []int32{
	11, // 0: postreport.PostReport.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: postreport.PostReport.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: postreport.CreatePostReportResponse.post_report:type_name -> postreport.PostReport
	0,  // 3: postreport.FindPostReportByIDResponse.post_report:type_name -> postreport.PostReport
	0,  // 4: postreport.FindAllPostReportsResponse.post_reports:type_name -> postreport.PostReport
	0,  // 5: postreport.PatchPostReportResponse.post_report:type_name -> postreport.PostReport
	1,  // 6: postreport.PostReportService.CreatePostReport:input_type -> postreport.CreatePostReportRequest
	3,  // 7: postreport.PostReportService.FindPostReportByID:input_type -> postreport.FindPostReportByIDRequest
	5,  // 8: postreport.PostReportService.FindAllPostReports:input_type -> postreport.FindAllPostReportsRequest
	7,  // 9: postreport.PostReportService.PatchPostReport:input_type -> postreport.PatchPostReportRequest
	9,  // 10: postreport.PostReportService.DeletePostReport:input_type -> postreport.DeletePostReportRequest
	2,  // 11: postreport.PostReportService.CreatePostReport:output_type -> postreport.CreatePostReportResponse
	4,  // 12: postreport.PostReportService.FindPostReportByID:output_type -> postreport.FindPostReportByIDResponse
	6,  // 13: postreport.PostReportService.FindAllPostReports:output_type -> postreport.FindAllPostReportsResponse
	8,  // 14: postreport.PostReportService.PatchPostReport:output_type -> postreport.PatchPostReportResponse
	10, // 15: postreport.PostReportService.DeletePostReport:output_type -> postreport.DeletePostReportResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_postreport_postreport_proto_init() }
func file_proto_postreport_postreport_proto_init() {
	if File_proto_postreport_postreport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_postreport_postreport_proto_rawDesc), len(file_proto_postreport_postreport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_postreport_postreport_proto_goTypes,
		DependencyIndexes: file_proto_postreport_postreport_proto_depIdxs,
		MessageInfos:      file_proto_postreport_postreport_proto_msgTypes,
	}.Build()
	File_proto_postreport_postreport_proto = out.File
	file_proto_postreport_postreport_proto_goTypes = nil
	file_proto_postreport_postreport_proto_depIdxs = nil
}
