// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/postlike/postlike.proto

package postlike

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLike) Reset() {
	*x = PostLike{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLike) ProtoMessage() {}

func (x *PostLike) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLike.ProtoReflect.Descriptor instead.
func (*PostLike) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{0}
}

func (x *PostLike) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostLike) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostLike) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePostLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostLikeRequest) Reset() {
	*x = CreatePostLikeRequest{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostLikeRequest) ProtoMessage() {}

func (x *CreatePostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostLikeRequest.ProtoReflect.Descriptor instead.
func (*CreatePostLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostLikeRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreatePostLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postlike      *PostLike              `protobuf:"bytes,1,opt,name=postlike,proto3" json:"postlike,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostLikeResponse) Reset() {
	*x = CreatePostLikeResponse{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostLikeResponse) ProtoMessage() {}

func (x *CreatePostLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostLikeResponse.ProtoReflect.Descriptor instead.
func (*CreatePostLikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostLikeResponse) GetPostlike() *PostLike {
	if x != nil {
		return x.Postlike
	}
	return nil
}

type FindAllPostLikesByPostIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllPostLikesByPostIDRequest) Reset() {
	*x = FindAllPostLikesByPostIDRequest{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllPostLikesByPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByPostIDRequest) ProtoMessage() {}

func (x *FindAllPostLikesByPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByPostIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByPostIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllPostLikesByPostIDRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type FindAllPostLikesByPostIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postlikes     []*PostLike            `protobuf:"bytes,1,rep,name=postlikes,proto3" json:"postlikes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllPostLikesByPostIDResponse) Reset() {
	*x = FindAllPostLikesByPostIDResponse{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllPostLikesByPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByPostIDResponse) ProtoMessage() {}

func (x *FindAllPostLikesByPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByPostIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByPostIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllPostLikesByPostIDResponse) GetPostlikes() []*PostLike {
	if x != nil {
		return x.Postlikes
	}
	return nil
}

type FindAllPostLikesByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllPostLikesByUserIDRequest) Reset() {
	*x = FindAllPostLikesByUserIDRequest{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllPostLikesByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByUserIDRequest) ProtoMessage() {}

func (x *FindAllPostLikesByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllPostLikesByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindAllPostLikesByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postlikes     []*PostLike            `protobuf:"bytes,1,rep,name=postlikes,proto3" json:"postlikes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllPostLikesByUserIDResponse) Reset() {
	*x = FindAllPostLikesByUserIDResponse{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllPostLikesByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostLikesByUserIDResponse) ProtoMessage() {}

func (x *FindAllPostLikesByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostLikesByUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllPostLikesByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllPostLikesByUserIDResponse) GetPostlikes() []*PostLike {
	if x != nil {
		return x.Postlikes
	}
	return nil
}

type DeletePostLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostLikeRequest) Reset() {
	*x = DeletePostLikeRequest{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeRequest) ProtoMessage() {}

func (x *DeletePostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeRequest.ProtoReflect.Descriptor instead.
func (*DeletePostLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePostLikeRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeletePostLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePostLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostLikeResponse) Reset() {
	*x = DeletePostLikeResponse{}
	mi := &file_proto_postlike_postlike_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostLikeResponse) ProtoMessage() {}

func (x *DeletePostLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_postlike_postlike_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostLikeResponse.ProtoReflect.Descriptor instead.
func (*DeletePostLikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_postlike_postlike_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostLikeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_postlike_postlike_proto protoreflect.FileDescriptor

const file_proto_postlike_postlike_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/postlike/postlike.proto\x12\bpostlike\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\bPostLike\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"I\n" +
	"\x15CreatePostLikeRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x16CreatePostLikeResponse\x12.\n" +
	"\bpostlike\x18\x01 \x01(\v2\x12.postlike.PostLikeR\bpostlike\":\n" +
	"\x1fFindAllPostLikesByPostIDRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\"T\n" +
	" FindAllPostLikesByPostIDResponse\x120\n" +
	"\tpostlikes\x18\x01 \x03(\v2\x12.postlike.PostLikeR\tpostlikes\":\n" +
	"\x1fFindAllPostLikesByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"T\n" +
	" FindAllPostLikesByUserIDResponse\x120\n" +
	"\tpostlikes\x18\x01 \x03(\v2\x12.postlike.PostLikeR\tpostlikes\"I\n" +
	"\x15DeletePostLikeRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x16DeletePostLikeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa1\x03\n" +
	"\x0fPostLikeService\x12S\n" +
	"\x0eCreatePostLike\x12\x1f.postlike.CreatePostLikeRequest\x1a .postlike.CreatePostLikeResponse\x12q\n" +
	"\x18FindAllPostLikesByPostID\x12).postlike.FindAllPostLikesByPostIDRequest\x1a*.postlike.FindAllPostLikesByPostIDResponse\x12q\n" +
	"\x18FindAllPostLikesByUserID\x12).postlike.FindAllPostLikesByUserIDRequest\x1a*.postlike.FindAllPostLikesByUserIDResponse\x12S\n" +
	"\x0eDeletePostLike\x12\x1f.postlike.DeletePostLikeRequest\x1a .postlike.DeletePostLikeResponseB\x10Z\x0eproto/postlikeb\x06proto3"

var (
	file_proto_postlike_postlike_proto_rawDescOnce sync.Once
	file_proto_postlike_postlike_proto_rawDescData []byte
)

func file_proto_postlike_postlike_proto_rawDescGZIP() []byte {
	file_proto_postlike_postlike_proto_rawDescOnce.Do(func() {
		file_proto_postlike_postlike_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_postlike_postlike_proto_rawDesc), len(file_proto_postlike_postlike_proto_rawDesc)))
	})
	return file_proto_postlike_postlike_proto_rawDescData
}

var file_proto_postlike_postlike_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_postlike_postlike_proto_goTypes = []any{
	(*PostLike)(nil),                         // 0: postlike.PostLike
	(*CreatePostLikeRequest)(nil),            // 1: postlike.CreatePostLikeRequest
	(*CreatePostLikeResponse)(nil),           // 2: postlike.CreatePostLikeResponse
	(*FindAllPostLikesByPostIDRequest)(nil),  // 3: postlike.FindAllPostLikesByPostIDRequest
	(*FindAllPostLikesByPostIDResponse)(nil), // 4: postlike.FindAllPostLikesByPostIDResponse
	(*FindAllPostLikesByUserIDRequest)(nil),  // 5: postlike.FindAllPostLikesByUserIDRequest
	(*FindAllPostLikesByUserIDResponse)(nil), // 6: postlike.FindAllPostLikesByUserIDResponse
	(*DeletePostLikeRequest)(nil),            // 7: postlike.DeletePostLikeRequest
	(*DeletePostLikeResponse)(nil),           // 8: postlike.DeletePostLikeResponse
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
}
var file_proto_postlike_postlike_proto_depIdxs = []int32{
	9, // 0: postlike.PostLike.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: postlike.CreatePostLikeResponse.postlike:type_name -> postlike.PostLike
	0, // 2: postlike.FindAllPostLikesByPostIDResponse.postlikes:type_name -> postlike.PostLike
	0, // 3: postlike.FindAllPostLikesByUserIDResponse.postlikes:type_name -> postlike.PostLike
	1, // 4: postlike.PostLikeService.CreatePostLike:input_type -> postlike.CreatePostLikeRequest
	3, // 5: postlike.PostLikeService.FindAllPostLikesByPostID:input_type -> postlike.FindAllPostLikesByPostIDRequest
	5, // 6: postlike.PostLikeService.FindAllPostLikesByUserID:input_type -> postlike.FindAllPostLikesByUserIDRequest
	7, // 7: postlike.PostLikeService.DeletePostLike:input_type -> postlike.DeletePostLikeRequest
	2, // 8: postlike.PostLikeService.CreatePostLike:output_type -> postlike.CreatePostLikeResponse
	4, // 9: postlike.PostLikeService.FindAllPostLikesByPostID:output_type -> postlike.FindAllPostLikesByPostIDResponse
	6, // 10: postlike.PostLikeService.FindAllPostLikesByUserID:output_type -> postlike.FindAllPostLikesByUserIDResponse
	8, // 11: postlike.PostLikeService.DeletePostLike:output_type -> postlike.DeletePostLikeResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_postlike_postlike_proto_init() }
func file_proto_postlike_postlike_proto_init() {
	if File_proto_postlike_postlike_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_postlike_postlike_proto_rawDesc), len(file_proto_postlike_postlike_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_postlike_postlike_proto_goTypes,
		DependencyIndexes: file_proto_postlike_postlike_proto_depIdxs,
		MessageInfos:      file_proto_postlike_postlike_proto_msgTypes,
	}.Build()
	File_proto_postlike_postlike_proto = out.File
	file_proto_postlike_postlike_proto_goTypes = nil
	file_proto_postlike_postlike_proto_depIdxs = nil
}
