// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/answer/answer.proto

package answer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        int32                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Question      string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,5,opt,name=answer,proto3" json:"answer,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_proto_answer_answer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Answer) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Answer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Answer) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Answer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Answer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnswerRequest) Reset() {
	*x = CreateAnswerRequest{}
	mi := &file_proto_answer_answer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerRequest) ProtoMessage() {}

func (x *CreateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerRequest.ProtoReflect.Descriptor instead.
func (*CreateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnswerRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAnswerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CreateAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type CreateAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        *Answer                `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnswerResponse) Reset() {
	*x = CreateAnswerResponse{}
	mi := &file_proto_answer_answer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerResponse) ProtoMessage() {}

func (x *CreateAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerResponse.ProtoReflect.Descriptor instead.
func (*CreateAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAnswerResponse) GetAnswer() *Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type FindAnswerByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAnswerByIDRequest) Reset() {
	*x = FindAnswerByIDRequest{}
	mi := &file_proto_answer_answer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAnswerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAnswerByIDRequest) ProtoMessage() {}

func (x *FindAnswerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAnswerByIDRequest.ProtoReflect.Descriptor instead.
func (*FindAnswerByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{3}
}

func (x *FindAnswerByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAnswerByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        *Answer                `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAnswerByIDResponse) Reset() {
	*x = FindAnswerByIDResponse{}
	mi := &file_proto_answer_answer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAnswerByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAnswerByIDResponse) ProtoMessage() {}

func (x *FindAnswerByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAnswerByIDResponse.ProtoReflect.Descriptor instead.
func (*FindAnswerByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{4}
}

func (x *FindAnswerByIDResponse) GetAnswer() *Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type FindAllAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllAnswersRequest) Reset() {
	*x = FindAllAnswersRequest{}
	mi := &file_proto_answer_answer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAnswersRequest) ProtoMessage() {}

func (x *FindAllAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAnswersRequest.ProtoReflect.Descriptor instead.
func (*FindAllAnswersRequest) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{5}
}

type FindAllAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*Answer              `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllAnswersResponse) Reset() {
	*x = FindAllAnswersResponse{}
	mi := &file_proto_answer_answer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAnswersResponse) ProtoMessage() {}

func (x *FindAllAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAnswersResponse.ProtoReflect.Descriptor instead.
func (*FindAllAnswersResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllAnswersResponse) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type FindAllAnswersByPostIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllAnswersByPostIDRequest) Reset() {
	*x = FindAllAnswersByPostIDRequest{}
	mi := &file_proto_answer_answer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllAnswersByPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAnswersByPostIDRequest) ProtoMessage() {}

func (x *FindAllAnswersByPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAnswersByPostIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllAnswersByPostIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllAnswersByPostIDRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type FindAllAnswersByPostIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*Answer              `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllAnswersByPostIDResponse) Reset() {
	*x = FindAllAnswersByPostIDResponse{}
	mi := &file_proto_answer_answer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllAnswersByPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAnswersByPostIDResponse) ProtoMessage() {}

func (x *FindAllAnswersByPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAnswersByPostIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllAnswersByPostIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllAnswersByPostIDResponse) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type DeleteAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnswerRequest) Reset() {
	*x = DeleteAnswerRequest{}
	mi := &file_proto_answer_answer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnswerRequest) ProtoMessage() {}

func (x *DeleteAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnswerRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAnswerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnswerResponse) Reset() {
	*x = DeleteAnswerResponse{}
	mi := &file_proto_answer_answer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnswerResponse) ProtoMessage() {}

func (x *DeleteAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_answer_answer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnswerResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_answer_answer_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAnswerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_answer_answer_proto protoreflect.FileDescriptor

const file_proto_answer_answer_proto_rawDesc = "" +
	"\n" +
	"\x19proto/answer/answer.proto\x12\x06answer\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x05 \x01(\tR\x06answer\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	"\x13CreateAnswerRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\">\n" +
	"\x14CreateAnswerResponse\x12&\n" +
	"\x06answer\x18\x01 \x01(\v2\x0e.answer.AnswerR\x06answer\"'\n" +
	"\x15FindAnswerByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"@\n" +
	"\x16FindAnswerByIDResponse\x12&\n" +
	"\x06answer\x18\x01 \x01(\v2\x0e.answer.AnswerR\x06answer\"\x17\n" +
	"\x15FindAllAnswersRequest\"B\n" +
	"\x16FindAllAnswersResponse\x12(\n" +
	"\aanswers\x18\x01 \x03(\v2\x0e.answer.AnswerR\aanswers\"8\n" +
	"\x1dFindAllAnswersByPostIDRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\"J\n" +
	"\x1eFindAllAnswersByPostIDResponse\x12(\n" +
	"\aanswers\x18\x01 \x03(\v2\x0e.answer.AnswerR\aanswers\"%\n" +
	"\x13DeleteAnswerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"0\n" +
	"\x14DeleteAnswerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb0\x03\n" +
	"\rAnswerService\x12I\n" +
	"\fCreateAnswer\x12\x1b.answer.CreateAnswerRequest\x1a\x1c.answer.CreateAnswerResponse\x12O\n" +
	"\x0eFindAnswerByID\x12\x1d.answer.FindAnswerByIDRequest\x1a\x1e.answer.FindAnswerByIDResponse\x12g\n" +
	"\x16FindAllAnswersByPostID\x12%.answer.FindAllAnswersByPostIDRequest\x1a&.answer.FindAllAnswersByPostIDResponse\x12O\n" +
	"\x0eFindAllAnswers\x12\x1d.answer.FindAllAnswersRequest\x1a\x1e.answer.FindAllAnswersResponse\x12I\n" +
	"\fDeleteAnswer\x12\x1b.answer.DeleteAnswerRequest\x1a\x1c.answer.DeleteAnswerResponseB\x0eZ\fproto/answerb\x06proto3"

var (
	file_proto_answer_answer_proto_rawDescOnce sync.Once
	file_proto_answer_answer_proto_rawDescData []byte
)

func file_proto_answer_answer_proto_rawDescGZIP() []byte {
	file_proto_answer_answer_proto_rawDescOnce.Do(func() {
		file_proto_answer_answer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_answer_answer_proto_rawDesc), len(file_proto_answer_answer_proto_rawDesc)))
	})
	return file_proto_answer_answer_proto_rawDescData
}

var file_proto_answer_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_answer_answer_proto_goTypes = []any{
	(*Answer)(nil),                         // 0: answer.Answer
	(*CreateAnswerRequest)(nil),            // 1: answer.CreateAnswerRequest
	(*CreateAnswerResponse)(nil),           // 2: answer.CreateAnswerResponse
	(*FindAnswerByIDRequest)(nil),          // 3: answer.FindAnswerByIDRequest
	(*FindAnswerByIDResponse)(nil),         // 4: answer.FindAnswerByIDResponse
	(*FindAllAnswersRequest)(nil),          // 5: answer.FindAllAnswersRequest
	(*FindAllAnswersResponse)(nil),         // 6: answer.FindAllAnswersResponse
	(*FindAllAnswersByPostIDRequest)(nil),  // 7: answer.FindAllAnswersByPostIDRequest
	(*FindAllAnswersByPostIDResponse)(nil), // 8: answer.FindAllAnswersByPostIDResponse
	(*DeleteAnswerRequest)(nil),            // 9: answer.DeleteAnswerRequest
	(*DeleteAnswerResponse)(nil),           // 10: answer.DeleteAnswerResponse
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
}
var file_proto_answer_answer_proto_depIdxs = []int32{
	11, // 0: answer.Answer.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: answer.CreateAnswerResponse.answer:type_name -> answer.Answer
	0,  // 2: answer.FindAnswerByIDResponse.answer:type_name -> answer.Answer
	0,  // 3: answer.FindAllAnswersResponse.answers:type_name -> answer.Answer
	0,  // 4: answer.FindAllAnswersByPostIDResponse.answers:type_name -> answer.Answer
	1,  // 5: answer.AnswerService.CreateAnswer:input_type -> answer.CreateAnswerRequest
	3,  // 6: answer.AnswerService.FindAnswerByID:input_type -> answer.FindAnswerByIDRequest
	7,  // 7: answer.AnswerService.FindAllAnswersByPostID:input_type -> answer.FindAllAnswersByPostIDRequest
	5,  // 8: answer.AnswerService.FindAllAnswers:input_type -> answer.FindAllAnswersRequest
	9,  // 9: answer.AnswerService.DeleteAnswer:input_type -> answer.DeleteAnswerRequest
	2,  // 10: answer.AnswerService.CreateAnswer:output_type -> answer.CreateAnswerResponse
	4,  // 11: answer.AnswerService.FindAnswerByID:output_type -> answer.FindAnswerByIDResponse
	8,  // 12: answer.AnswerService.FindAllAnswersByPostID:output_type -> answer.FindAllAnswersByPostIDResponse
	6,  // 13: answer.AnswerService.FindAllAnswers:output_type -> answer.FindAllAnswersResponse
	10, // 14: answer.AnswerService.DeleteAnswer:output_type -> answer.DeleteAnswerResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_answer_answer_proto_init() }
func file_proto_answer_answer_proto_init() {
	if File_proto_answer_answer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_answer_answer_proto_rawDesc), len(file_proto_answer_answer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_answer_answer_proto_goTypes,
		DependencyIndexes: file_proto_answer_answer_proto_depIdxs,
		MessageInfos:      file_proto_answer_answer_proto_msgTypes,
	}.Build()
	File_proto_answer_answer_proto = out.File
	file_proto_answer_answer_proto_goTypes = nil
	file_proto_answer_answer_proto_depIdxs = nil
}
