// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/teamrequest/teamrequest.proto

package teamrequest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TeamRequest message
type TeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	RequestBy     string                 `protobuf:"bytes,2,opt,name=request_by,json=requestBy,proto3" json:"request_by,omitempty"`
	RequestTo     string                 `protobuf:"bytes,3,opt,name=request_to,json=requestTo,proto3" json:"request_to,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamRequest) Reset() {
	*x = TeamRequest{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamRequest) ProtoMessage() {}

func (x *TeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamRequest.ProtoReflect.Descriptor instead.
func (*TeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{0}
}

func (x *TeamRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *TeamRequest) GetRequestBy() string {
	if x != nil {
		return x.RequestBy
	}
	return ""
}

func (x *TeamRequest) GetRequestTo() string {
	if x != nil {
		return x.RequestTo
	}
	return ""
}

func (x *TeamRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Create
type CreateTeamRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	RequestBy     string                 `protobuf:"bytes,2,opt,name=request_by,json=requestBy,proto3" json:"request_by,omitempty"`
	RequestTo     string                 `protobuf:"bytes,3,opt,name=request_to,json=requestTo,proto3" json:"request_to,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequestRequest) Reset() {
	*x = CreateTeamRequestRequest{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequestRequest) ProtoMessage() {}

func (x *CreateTeamRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamRequestRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateTeamRequestRequest) GetRequestBy() string {
	if x != nil {
		return x.RequestBy
	}
	return ""
}

func (x *CreateTeamRequestRequest) GetRequestTo() string {
	if x != nil {
		return x.RequestTo
	}
	return ""
}

func (x *CreateTeamRequestRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateTeamRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamRequest   *TeamRequest           `protobuf:"bytes,1,opt,name=team_request,json=teamRequest,proto3" json:"team_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequestResponse) Reset() {
	*x = CreateTeamRequestResponse{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequestResponse) ProtoMessage() {}

func (x *CreateTeamRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTeamRequestResponse) GetTeamRequest() *TeamRequest {
	if x != nil {
		return x.TeamRequest
	}
	return nil
}

// Find by ID
type FindTeamRequestByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	RequestBy     string                 `protobuf:"bytes,2,opt,name=request_by,json=requestBy,proto3" json:"request_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTeamRequestByIDRequest) Reset() {
	*x = FindTeamRequestByIDRequest{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTeamRequestByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTeamRequestByIDRequest) ProtoMessage() {}

func (x *FindTeamRequestByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTeamRequestByIDRequest.ProtoReflect.Descriptor instead.
func (*FindTeamRequestByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{3}
}

func (x *FindTeamRequestByIDRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FindTeamRequestByIDRequest) GetRequestBy() string {
	if x != nil {
		return x.RequestBy
	}
	return ""
}

type FindTeamRequestByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamRequest   *TeamRequest           `protobuf:"bytes,1,opt,name=team_request,json=teamRequest,proto3" json:"team_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTeamRequestByIDResponse) Reset() {
	*x = FindTeamRequestByIDResponse{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTeamRequestByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTeamRequestByIDResponse) ProtoMessage() {}

func (x *FindTeamRequestByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTeamRequestByIDResponse.ProtoReflect.Descriptor instead.
func (*FindTeamRequestByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{4}
}

func (x *FindTeamRequestByIDResponse) GetTeamRequest() *TeamRequest {
	if x != nil {
		return x.TeamRequest
	}
	return nil
}

// Find all by PostID
type FindAllByPostIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByPostIDRequest) Reset() {
	*x = FindAllByPostIDRequest{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByPostIDRequest) ProtoMessage() {}

func (x *FindAllByPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByPostIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllByPostIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllByPostIDRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type FindAllByPostIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamRequests  []*TeamRequest         `protobuf:"bytes,1,rep,name=team_requests,json=teamRequests,proto3" json:"team_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByPostIDResponse) Reset() {
	*x = FindAllByPostIDResponse{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByPostIDResponse) ProtoMessage() {}

func (x *FindAllByPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByPostIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllByPostIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllByPostIDResponse) GetTeamRequests() []*TeamRequest {
	if x != nil {
		return x.TeamRequests
	}
	return nil
}

// NEW: Find all by RequestBy
type FindAllByRequestByRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestBy     string                 `protobuf:"bytes,1,opt,name=request_by,json=requestBy,proto3" json:"request_by,omitempty"` // user UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByRequestByRequest) Reset() {
	*x = FindAllByRequestByRequest{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByRequestByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByRequestByRequest) ProtoMessage() {}

func (x *FindAllByRequestByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByRequestByRequest.ProtoReflect.Descriptor instead.
func (*FindAllByRequestByRequest) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllByRequestByRequest) GetRequestBy() string {
	if x != nil {
		return x.RequestBy
	}
	return ""
}

type FindAllByRequestByResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamRequests  []*TeamRequest         `protobuf:"bytes,1,rep,name=team_requests,json=teamRequests,proto3" json:"team_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByRequestByResponse) Reset() {
	*x = FindAllByRequestByResponse{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByRequestByResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByRequestByResponse) ProtoMessage() {}

func (x *FindAllByRequestByResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByRequestByResponse.ProtoReflect.Descriptor instead.
func (*FindAllByRequestByResponse) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllByRequestByResponse) GetTeamRequests() []*TeamRequest {
	if x != nil {
		return x.TeamRequests
	}
	return nil
}

// Patch
type PatchTeamRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	RequestBy     string                 `protobuf:"bytes,2,opt,name=request_by,json=requestBy,proto3" json:"request_by,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchTeamRequestRequest) Reset() {
	*x = PatchTeamRequestRequest{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchTeamRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchTeamRequestRequest) ProtoMessage() {}

func (x *PatchTeamRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchTeamRequestRequest.ProtoReflect.Descriptor instead.
func (*PatchTeamRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{9}
}

func (x *PatchTeamRequestRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PatchTeamRequestRequest) GetRequestBy() string {
	if x != nil {
		return x.RequestBy
	}
	return ""
}

func (x *PatchTeamRequestRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PatchTeamRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamRequest   *TeamRequest           `protobuf:"bytes,1,opt,name=team_request,json=teamRequest,proto3" json:"team_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchTeamRequestResponse) Reset() {
	*x = PatchTeamRequestResponse{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchTeamRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchTeamRequestResponse) ProtoMessage() {}

func (x *PatchTeamRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchTeamRequestResponse.ProtoReflect.Descriptor instead.
func (*PatchTeamRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{10}
}

func (x *PatchTeamRequestResponse) GetTeamRequest() *TeamRequest {
	if x != nil {
		return x.TeamRequest
	}
	return nil
}

// Delete
type DeleteTeamRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	RequestBy     string                 `protobuf:"bytes,2,opt,name=request_by,json=requestBy,proto3" json:"request_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequestRequest) Reset() {
	*x = DeleteTeamRequestRequest{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequestRequest) ProtoMessage() {}

func (x *DeleteTeamRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequestRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTeamRequestRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeleteTeamRequestRequest) GetRequestBy() string {
	if x != nil {
		return x.RequestBy
	}
	return ""
}

type DeleteTeamRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequestResponse) Reset() {
	*x = DeleteTeamRequestResponse{}
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequestResponse) ProtoMessage() {}

func (x *DeleteTeamRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teamrequest_teamrequest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequestResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_teamrequest_teamrequest_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTeamRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_teamrequest_teamrequest_proto protoreflect.FileDescriptor

const file_proto_teamrequest_teamrequest_proto_rawDesc = "" +
	"\n" +
	"#proto/teamrequest/teamrequest.proto\x12\vteamrequest\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\vTeamRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x1d\n" +
	"\n" +
	"request_by\x18\x02 \x01(\tR\trequestBy\x12\x1d\n" +
	"\n" +
	"request_to\x18\x03 \x01(\tR\trequestTo\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x89\x01\n" +
	"\x18CreateTeamRequestRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x1d\n" +
	"\n" +
	"request_by\x18\x02 \x01(\tR\trequestBy\x12\x1d\n" +
	"\n" +
	"request_to\x18\x03 \x01(\tR\trequestTo\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"X\n" +
	"\x19CreateTeamRequestResponse\x12;\n" +
	"\fteam_request\x18\x01 \x01(\v2\x18.teamrequest.TeamRequestR\vteamRequest\"T\n" +
	"\x1aFindTeamRequestByIDRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x1d\n" +
	"\n" +
	"request_by\x18\x02 \x01(\tR\trequestBy\"Z\n" +
	"\x1bFindTeamRequestByIDResponse\x12;\n" +
	"\fteam_request\x18\x01 \x01(\v2\x18.teamrequest.TeamRequestR\vteamRequest\"1\n" +
	"\x16FindAllByPostIDRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\"X\n" +
	"\x17FindAllByPostIDResponse\x12=\n" +
	"\rteam_requests\x18\x01 \x03(\v2\x18.teamrequest.TeamRequestR\fteamRequests\":\n" +
	"\x19FindAllByRequestByRequest\x12\x1d\n" +
	"\n" +
	"request_by\x18\x01 \x01(\tR\trequestBy\"[\n" +
	"\x1aFindAllByRequestByResponse\x12=\n" +
	"\rteam_requests\x18\x01 \x03(\v2\x18.teamrequest.TeamRequestR\fteamRequests\"i\n" +
	"\x17PatchTeamRequestRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x1d\n" +
	"\n" +
	"request_by\x18\x02 \x01(\tR\trequestBy\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"W\n" +
	"\x18PatchTeamRequestResponse\x12;\n" +
	"\fteam_request\x18\x01 \x01(\v2\x18.teamrequest.TeamRequestR\vteamRequest\"R\n" +
	"\x18DeleteTeamRequestRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x1d\n" +
	"\n" +
	"request_by\x18\x02 \x01(\tR\trequestBy\"5\n" +
	"\x19DeleteTeamRequestResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xec\x04\n" +
	"\x12TeamRequestService\x12b\n" +
	"\x11CreateTeamRequest\x12%.teamrequest.CreateTeamRequestRequest\x1a&.teamrequest.CreateTeamRequestResponse\x12h\n" +
	"\x13FindTeamRequestByID\x12'.teamrequest.FindTeamRequestByIDRequest\x1a(.teamrequest.FindTeamRequestByIDResponse\x12\\\n" +
	"\x0fFindAllByPostID\x12#.teamrequest.FindAllByPostIDRequest\x1a$.teamrequest.FindAllByPostIDResponse\x12e\n" +
	"\x12FindAllByRequestBy\x12&.teamrequest.FindAllByRequestByRequest\x1a'.teamrequest.FindAllByRequestByResponse\x12_\n" +
	"\x10PatchTeamRequest\x12$.teamrequest.PatchTeamRequestRequest\x1a%.teamrequest.PatchTeamRequestResponse\x12b\n" +
	"\x11DeleteTeamRequest\x12%.teamrequest.DeleteTeamRequestRequest\x1a&.teamrequest.DeleteTeamRequestResponseB\x13Z\x11proto/teamrequestb\x06proto3"

var (
	file_proto_teamrequest_teamrequest_proto_rawDescOnce sync.Once
	file_proto_teamrequest_teamrequest_proto_rawDescData []byte
)

func file_proto_teamrequest_teamrequest_proto_rawDescGZIP() []byte {
	file_proto_teamrequest_teamrequest_proto_rawDescOnce.Do(func() {
		file_proto_teamrequest_teamrequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_teamrequest_teamrequest_proto_rawDesc), len(file_proto_teamrequest_teamrequest_proto_rawDesc)))
	})
	return file_proto_teamrequest_teamrequest_proto_rawDescData
}

var file_proto_teamrequest_teamrequest_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_teamrequest_teamrequest_proto_goTypes = []any{
	(*TeamRequest)(nil),                 // 0: teamrequest.TeamRequest
	(*CreateTeamRequestRequest)(nil),    // 1: teamrequest.CreateTeamRequestRequest
	(*CreateTeamRequestResponse)(nil),   // 2: teamrequest.CreateTeamRequestResponse
	(*FindTeamRequestByIDRequest)(nil),  // 3: teamrequest.FindTeamRequestByIDRequest
	(*FindTeamRequestByIDResponse)(nil), // 4: teamrequest.FindTeamRequestByIDResponse
	(*FindAllByPostIDRequest)(nil),      // 5: teamrequest.FindAllByPostIDRequest
	(*FindAllByPostIDResponse)(nil),     // 6: teamrequest.FindAllByPostIDResponse
	(*FindAllByRequestByRequest)(nil),   // 7: teamrequest.FindAllByRequestByRequest
	(*FindAllByRequestByResponse)(nil),  // 8: teamrequest.FindAllByRequestByResponse
	(*PatchTeamRequestRequest)(nil),     // 9: teamrequest.PatchTeamRequestRequest
	(*PatchTeamRequestResponse)(nil),    // 10: teamrequest.PatchTeamRequestResponse
	(*DeleteTeamRequestRequest)(nil),    // 11: teamrequest.DeleteTeamRequestRequest
	(*DeleteTeamRequestResponse)(nil),   // 12: teamrequest.DeleteTeamRequestResponse
}
var file_proto_teamrequest_teamrequest_proto_depIdxs = []int32{
	0,  // 0: teamrequest.CreateTeamRequestResponse.team_request:type_name -> teamrequest.TeamRequest
	0,  // 1: teamrequest.FindTeamRequestByIDResponse.team_request:type_name -> teamrequest.TeamRequest
	0,  // 2: teamrequest.FindAllByPostIDResponse.team_requests:type_name -> teamrequest.TeamRequest
	0,  // 3: teamrequest.FindAllByRequestByResponse.team_requests:type_name -> teamrequest.TeamRequest
	0,  // 4: teamrequest.PatchTeamRequestResponse.team_request:type_name -> teamrequest.TeamRequest
	1,  // 5: teamrequest.TeamRequestService.CreateTeamRequest:input_type -> teamrequest.CreateTeamRequestRequest
	3,  // 6: teamrequest.TeamRequestService.FindTeamRequestByID:input_type -> teamrequest.FindTeamRequestByIDRequest
	5,  // 7: teamrequest.TeamRequestService.FindAllByPostID:input_type -> teamrequest.FindAllByPostIDRequest
	7,  // 8: teamrequest.TeamRequestService.FindAllByRequestBy:input_type -> teamrequest.FindAllByRequestByRequest
	9,  // 9: teamrequest.TeamRequestService.PatchTeamRequest:input_type -> teamrequest.PatchTeamRequestRequest
	11, // 10: teamrequest.TeamRequestService.DeleteTeamRequest:input_type -> teamrequest.DeleteTeamRequestRequest
	2,  // 11: teamrequest.TeamRequestService.CreateTeamRequest:output_type -> teamrequest.CreateTeamRequestResponse
	4,  // 12: teamrequest.TeamRequestService.FindTeamRequestByID:output_type -> teamrequest.FindTeamRequestByIDResponse
	6,  // 13: teamrequest.TeamRequestService.FindAllByPostID:output_type -> teamrequest.FindAllByPostIDResponse
	8,  // 14: teamrequest.TeamRequestService.FindAllByRequestBy:output_type -> teamrequest.FindAllByRequestByResponse
	10, // 15: teamrequest.TeamRequestService.PatchTeamRequest:output_type -> teamrequest.PatchTeamRequestResponse
	12, // 16: teamrequest.TeamRequestService.DeleteTeamRequest:output_type -> teamrequest.DeleteTeamRequestResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_teamrequest_teamrequest_proto_init() }
func file_proto_teamrequest_teamrequest_proto_init() {
	if File_proto_teamrequest_teamrequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_teamrequest_teamrequest_proto_rawDesc), len(file_proto_teamrequest_teamrequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_teamrequest_teamrequest_proto_goTypes,
		DependencyIndexes: file_proto_teamrequest_teamrequest_proto_depIdxs,
		MessageInfos:      file_proto_teamrequest_teamrequest_proto_msgTypes,
	}.Build()
	File_proto_teamrequest_teamrequest_proto = out.File
	file_proto_teamrequest_teamrequest_proto_goTypes = nil
	file_proto_teamrequest_teamrequest_proto_depIdxs = nil
}
